# Generated by Django 4.2.23 on 2025-07-06 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorName', models.CharField(max_length=100)),
                ('donorType', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('itemType', models.CharField(max_length=100)),
                ('foodCategory', models.CharField(choices=[('raw', 'Raw'), ('cooked', 'Cooked'), ('packaged', 'Packaged')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('quantityUnit', models.CharField(choices=[('kg', 'Kilograms'), ('L', 'Liters'), ('packs', 'Packs')], max_length=10)),
                ('pickupRequired', models.BooleanField()),
                ('isPerishable', models.BooleanField()),
                ('address', models.TextField()),
                ('DonateTime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
