# Generated by Django 4.2.23 on 2025-07-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='drop_location',
            field=models.CharField(blank=True, choices=[('center1', 'Center 1'), ('center2', 'Center 2'), ('center3', 'Center 3')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
